# Generated by Django 4.2.4 on 2023-09-26 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0005_alter_fotografia_foto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fotografia',
            options={'permissions': (('buscar_no_site', 'Permitir o usuario realizar busca no site'),)},
        ),
    ]
